In [1]:
import numpy as np
l1 = [1,2,3,4]
l2 = [10,20,30,40]
l3= []
for i in range(len(l1)):
    l3.append(l1[i]+l2[i])

print(l3)

[11, 22, 33, 44]


In [2]:
import numpy as np
l1 = [1,2,3,4]
l2 = [10,20,30,40]

a1 = np.array(l1)#np array is taking the values from python, internally it stores in a array[]
a2 = np.array(l2)
a3 = a1+a2

print(a3)

[11 22 33 44]


In [ ]:
import time
import numpy as np
num = 10_0000_000
count = num
l1=list(range(count))
l2=list(range(count))

import sys
print("Size of l1 {}", sys.getsizeof(l1))

start=time.time()
list3 = [l1[i]+l2[i] for i in range(num)]
end=time.time()
elapsed = 1000*(end-start)
print("List time:",elapsed)

Size of l1 {} 800000056


In [4]:
import time
import numpy as np
num = 10_0000_000
count = num

start = time.time()
a1 = np.arange(num)
a2 = np.arange(num)
a3 = a1+a2
end = time.time()
print("Time took to add two np arrays!!! = {}", end-start)


Time took to add two np arrays!!! = {} 0.9848310947418213


In [5]:
print(a1.shape)

(100000000,)


In [9]:
import numpy as np
a1 = np.linspace(0,9,19)# 1, 1.5,2,2.5
for i in a1:
    print(i)


0.0
0.5
1.0
1.5
2.0
2.5
3.0
3.5
4.0
4.5
5.0
5.5
6.0
6.5
7.0
7.5
8.0
8.5
9.0


In [1]:
import time
import numpy as np
num = 1000_000
count = num
l1=list(range(count)) # 64bits for number 
import sys
print("Size of l1 {}", sys.getsizeof(l1))

a1 = np.arange(count,dtype="int32") # Enforcing to 32-bit
print("Size of a1 {}", a1.nbytes)

Size of l1 {} 8000056
Size of a1 {} 4000000


In [10]:
import numpy as np
a = np.zeros(100)
print(a.all())
b = np.ones(100)
print(b.all()) # None of the elment is 0, all are greater than or equal to 1

c = np.array([1,2,4,0]) # 1x4
print("any = {}", c.any())
d = c.reshape((2,2))
print(d)


False
True
any = {} True
[[1 2]
 [4 0]]


In [15]:
c = np.array([1,2,4,5.5]) # 1x4
print(c.dtype)
c+2

float64


array([3. , 4. , 6. , 7.5])

In [14]:
c = np.array([1,2,4]) # 1x4
print(c.dtype)
c+2

int64


array([3, 4, 6])

In [16]:
l1 = [0,1,2,3,4,5,6,7,8,9]
print(l1[::2]) # start:stop:increment 

[0, 2, 4, 6, 8]


In [19]:
a1 = np.arange(100)
a2 = a1.reshape((10,10))
print(a2)
print(a2[::2,::2])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[ 0  2  4  6  8]
 [20 22 24 26 28]
 [40 42 44 46 48]
 [60 62 64 66 68]
 [80 82 84 86 88]]
